version: '3.8'

services:
  app:
    build: .
    container_name: faq_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/faqs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    container_name: faq_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: faq_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
